[package]
name = "benchmarking_symmetric_encryption_in_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1"


[dev-dependencies]
criterion = "0.4"
rand = "0.8"

[[bench]]
name = "crypto"
harness = false
